# SPDX-FileCopyrightText: 2026 Juan de la Cruz García <delacruzgarciajuan@gmail.com>
# SPDX-License-Identifier: GPL-3.0-or-later

"""Project persistence: the ``.gifforge`` container, recents, and autosave.

Container layout (a zip archive):

    project.json          # manifest (version, frames, output format, metadata)
    frames/00001.png      # one PNG per *unique* source frame
    ...

Duplicated frames (which share a source PNG) are stored once and referenced
multiple times in the manifest, so projects stay compact. The manifest carries
a ``version`` so future format changes can be detected and rejected cleanly.
"""

from __future__ import annotations

import json
import logging
import re
import time
import zipfile
from pathlib import Path
from typing import List

from ..frames.model import Frame, FrameList
from ..models import OutputFormat
from ..utils import cache_dir
from .cache import SessionCache
from .document import PROJECT_VERSION, ProjectDocument

log = logging.getLogger(__name__)

_MANIFEST = "project.json"

# Containers can come from third parties; bound what we are willing to extract
# so a hostile archive can't zip-bomb the cache directory.
_MAX_FRAMES = 20_000
_MAX_FRAME_BYTES = 64 * 1024 * 1024
# Archive frame names are generated by save_project; anything else (nested
# paths, non-PNG, …) is rejected before extraction.
_FRAME_NAME_RE = re.compile(r"frames/\d{1,6}\.png")


class ProjectError(Exception):
    pass


# --- save / load --------------------------------------------------------------


def save_project(document: ProjectDocument, dest: Path) -> Path:
    """Write *document* to *dest* as a ``.gifforge`` container."""
    dest = Path(dest)
    if not document.created:
        document.created = time.strftime("%Y-%m-%dT%H:%M:%S")

    archive_names: dict[str, str] = {}
    manifest_frames: List[dict] = []

    # Write to a temp file then move, so an interrupted save can't corrupt dest.
    tmp = dest.with_name(dest.name + ".tmp")
    try:
        with zipfile.ZipFile(tmp, "w", zipfile.ZIP_DEFLATED) as archive:
            for frame in document.frames:
                src = str(frame.path)
                if src not in archive_names:
                    name = f"frames/{len(archive_names) + 1:05d}.png"
                    archive_names[src] = name
                    archive.write(src, name)
                manifest_frames.append({
                    "file": archive_names[src],
                    "delay_ms": frame.delay_ms,
                    "source_index": frame.source_index,
                })
            manifest = {
                "version": PROJECT_VERSION,
                "app": "GIF Forge",
                "created": document.created,
                "output_format": document.output_format.value,
                "frames": manifest_frames,
                "overlays": [o.to_dict() for o in document.overlays],
                "metadata": document.metadata,
            }
            archive.writestr(_MANIFEST, json.dumps(manifest, indent=2))
        tmp.replace(dest)
    except BaseException:
        tmp.unlink(missing_ok=True)
        raise
    document.path = dest
    log.info("saved project %s (%d frames)", dest, len(document.frames))
    return dest


def load_project(path: Path, cache: SessionCache | None = None) -> ProjectDocument:
    """Load a ``.gifforge`` container, extracting frames into *cache*."""
    path = Path(path)
    cache = cache or SessionCache()
    try:
        with zipfile.ZipFile(path) as archive:
            manifest = json.loads(archive.read(_MANIFEST))
            version = manifest.get("version")
            if version != PROJECT_VERSION:
                raise ProjectError(
                    f"unsupported project version {version} "
                    f"(this build understands {PROJECT_VERSION})"
                )
            entries = manifest["frames"]
            if not isinstance(entries, list) or len(entries) > _MAX_FRAMES:
                raise ProjectError("frame list missing or too large")
            extracted: dict[str, Path] = {}
            frames: List[Frame] = []
            for entry in entries:
                arc = entry["file"]
                if not isinstance(arc, str) or not _FRAME_NAME_RE.fullmatch(arc):
                    raise ProjectError(f"illegal frame entry name: {arc!r}")
                if arc not in extracted:
                    if archive.getinfo(arc).file_size > _MAX_FRAME_BYTES:
                        raise ProjectError(f"frame {arc} exceeds the size limit")
                    out = cache.frames_dir / Path(arc).name
                    out.write_bytes(archive.read(arc))
                    extracted[arc] = out
                frames.append(
                    Frame(
                        extracted[arc],
                        int(entry["delay_ms"]),
                        int(entry["source_index"]),
                    )
                )
    except (KeyError, TypeError, ValueError, zipfile.BadZipFile) as exc:
        raise ProjectError(f"not a valid GIF Forge project: {exc}") from exc

    from ..editor.overlays import overlay_from_dict

    overlays = [overlay_from_dict(o) for o in manifest.get("overlays", [])]
    return ProjectDocument(
        frames=FrameList(frames),
        output_format=OutputFormat.from_value(manifest.get("output_format", "gif")),
        created=manifest.get("created", ""),
        path=path,
        overlays=overlays,
        metadata=manifest.get("metadata", {}),
    )


# --- recent projects ----------------------------------------------------------


class RecentProjects:
    def __init__(self, path: Path | None = None, limit: int = 10) -> None:
        self._path = path or (_config_dir() / "recents.json")
        self._limit = limit

    def add(self, project_path: Path) -> None:
        items = [str(Path(project_path).resolve())]
        for existing in self._read():
            if existing not in items:
                items.append(existing)
        self._write(items[: self._limit])

    def list(self) -> List[Path]:
        """Existing recent projects, most-recent first; prunes missing files."""
        items = self._read()
        result = [Path(p) for p in items if Path(p).exists()]
        # Rewrite if any were pruned.
        if len(result) != len(items):
            self._write([str(p) for p in result])
        return result

    def _read(self) -> List[str]:
        try:
            items = json.loads(self._path.read_text())
        except (OSError, ValueError):
            return []
        if not isinstance(items, list):
            return []
        return [p for p in items if isinstance(p, str)]

    def _write(self, items: List[str]) -> None:
        self._path.parent.mkdir(parents=True, exist_ok=True)
        tmp = self._path.with_name(self._path.name + ".tmp")
        tmp.write_text(json.dumps(items, indent=2))
        tmp.replace(self._path)


# --- autosave / crash recovery ------------------------------------------------


def _config_dir() -> Path:
    import os

    base = os.environ.get("XDG_CONFIG_HOME") or os.path.expanduser("~/.config")
    from .. import APP_ID

    path = Path(base) / APP_ID
    path.mkdir(parents=True, exist_ok=True)
    return path


def autosave_dir() -> Path:
    path = cache_dir() / "autosave"
    path.mkdir(parents=True, exist_ok=True)
    return path


def autosave(document: ProjectDocument, session_id: str) -> Path:
    """Write a recovery snapshot for *session_id* (cleared on clean close)."""
    return save_project(document, autosave_dir() / f"{session_id}.gifforge")


def clear_autosave(session_id: str) -> None:
    (autosave_dir() / f"{session_id}.gifforge").unlink(missing_ok=True)


def list_recoverable() -> List[Path]:
    """Autosave snapshots left behind by a previous (crashed) session."""
    return sorted(autosave_dir().glob("*.gifforge"))
